/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChefsRouteRouteImport } from './routes/chefs/route'
import { Route as RequestRouteRouteImport } from './routes/request/route'
import { Route as ChefsIndexRouteImport } from './routes/chefs/index'
import { Route as ChefsChefIdRouteImport } from './routes/chefs/$chefId'
import { Route as RequestIndexRouteImport } from './routes/request/index'
import { Route as RequestProposalsRouteImport } from './routes/request/proposals'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChefsRouteRoute = ChefsRouteRouteImport.update({
  id: '/chefs',
  path: '/chefs',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestRouteRoute = RequestRouteRouteImport.update({
  id: '/request',
  path: '/request',
  getParentRoute: () => rootRouteImport,
} as any)
const ChefsIndexRoute = ChefsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChefsRouteRoute,
} as any)
const ChefsChefIdRoute = ChefsChefIdRouteImport.update({
  id: '/$chefId',
  path: '/$chefId',
  getParentRoute: () => ChefsRouteRoute,
} as any)
const RequestIndexRoute = RequestIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RequestRouteRoute,
} as any)
const RequestProposalsRoute = RequestProposalsRouteImport.update({
  id: '/proposals',
  path: '/proposals',
  getParentRoute: () => RequestRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chefs': typeof ChefsRouteRouteWithChildren
  '/request': typeof RequestRouteRouteWithChildren
  '/chefs/$chefId': typeof ChefsChefIdRoute
  '/request/proposals': typeof RequestProposalsRoute
  '/chefs/': typeof ChefsIndexRoute
  '/request/': typeof RequestIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chefs/$chefId': typeof ChefsChefIdRoute
  '/request/proposals': typeof RequestProposalsRoute
  '/chefs': typeof ChefsIndexRoute
  '/request': typeof RequestIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chefs': typeof ChefsRouteRouteWithChildren
  '/request': typeof RequestRouteRouteWithChildren
  '/chefs/$chefId': typeof ChefsChefIdRoute
  '/request/proposals': typeof RequestProposalsRoute
  '/chefs/': typeof ChefsIndexRoute
  '/request/': typeof RequestIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chefs'
    | '/request'
    | '/chefs/$chefId'
    | '/request/proposals'
    | '/chefs/'
    | '/request/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/chefs/$chefId' | '/request/proposals' | '/chefs' | '/request'
  id:
    | '__root__'
    | '/'
    | '/chefs'
    | '/request'
    | '/chefs/$chefId'
    | '/request/proposals'
    | '/chefs/'
    | '/request/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChefsRouteRoute: typeof ChefsRouteRouteWithChildren
  RequestRouteRoute: typeof RequestRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chefs': {
      id: '/chefs'
      path: '/chefs'
      fullPath: '/chefs'
      preLoaderRoute: typeof ChefsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request': {
      id: '/request'
      path: '/request'
      fullPath: '/request'
      preLoaderRoute: typeof RequestRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chefs/': {
      id: '/chefs/'
      path: '/'
      fullPath: '/chefs/'
      preLoaderRoute: typeof ChefsIndexRouteImport
      parentRoute: typeof ChefsRouteRoute
    }
    '/chefs/$chefId': {
      id: '/chefs/$chefId'
      path: '/$chefId'
      fullPath: '/chefs/$chefId'
      preLoaderRoute: typeof ChefsChefIdRouteImport
      parentRoute: typeof ChefsRouteRoute
    }
    '/request/': {
      id: '/request/'
      path: '/'
      fullPath: '/request/'
      preLoaderRoute: typeof RequestIndexRouteImport
      parentRoute: typeof RequestRouteRoute
    }
    '/request/proposals': {
      id: '/request/proposals'
      path: '/proposals'
      fullPath: '/request/proposals'
      preLoaderRoute: typeof RequestProposalsRouteImport
      parentRoute: typeof RequestRouteRoute
    }
  }
}

interface ChefsRouteRouteChildren {
  ChefsChefIdRoute: typeof ChefsChefIdRoute
  ChefsIndexRoute: typeof ChefsIndexRoute
}

const ChefsRouteRouteChildren: ChefsRouteRouteChildren = {
  ChefsChefIdRoute: ChefsChefIdRoute,
  ChefsIndexRoute: ChefsIndexRoute,
}

const ChefsRouteRouteWithChildren = ChefsRouteRoute._addFileChildren(
  ChefsRouteRouteChildren,
)

interface RequestRouteRouteChildren {
  RequestProposalsRoute: typeof RequestProposalsRoute
  RequestIndexRoute: typeof RequestIndexRoute
}

const RequestRouteRouteChildren: RequestRouteRouteChildren = {
  RequestProposalsRoute: RequestProposalsRoute,
  RequestIndexRoute: RequestIndexRoute,
}

const RequestRouteRouteWithChildren = RequestRouteRoute._addFileChildren(
  RequestRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChefsRouteRoute: ChefsRouteRouteWithChildren,
  RequestRouteRoute: RequestRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
